# Generated by Django 5.1.2 on 2024-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_slot',
            field=models.CharField(max_length=10),
        ),
    ]
