# Generated by Django 5.1.2 on 2024-10-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('semester', models.CharField(max_length=10)),
                ('exam_slot', models.CharField(max_length=10)),
            ],
        ),
    ]
